# Site settings
title: QuqqU
description: "QuqqU's Blog"
url: "http://www.QuqqU.github.io/"
ogimage: "img/favicon.png"
author:
  name: "QuqqU"
  email: "rldnd913@naver.com"
  url: "https://QuqqU.github.io"


# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 2
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
